export default [
  {
    type: "text",
    value: "",
    name: "productName",
    id: "product-name",
    placeholder: "Product name",
    label: "Product Name",
  },
  {
    type: "url",
    value: "",
    name: "imageURL",
    id: "image-url",
    placeholder: "Image URL",
    label: "Image URL",
  },
  {
    type: "date",
    value: "",
    name: "expiryDate",
    id: "date",
    placeholder: "",
    label: "Expiration Date",
  },
  {
    type: "number",
    value: "",
    name: "quantity",
    id: "quantity",
    placeholder: "Quantity Purchased",
    label: "Quantity purchased",
  },
  {
    type: "number",
    value: "",
    name: "weightPerItem",
    id: "weightPerItem",
    placeholder: "Weight Per Item",
    label: "Weight per Item",
  },
  // {
  //   type: "number",
  //   name: "total",
  //   id: "total",
  //   placeholder: "total",
  //   label: "Total",
  // },
]
